// generated by Fast Light User Interface Designer (fluid) version 1,0400

#ifndef Application_h
#define Application_h
#include <FL/Fl.H>
#include<Fr_Core.h>
#include<Fr_GL3Window.h>


class Application : public Fr_GL3Window {
public:
    Application(int x = 0, int y = 0, int w = 1530, int h = 800, const char* l = "Design456App");
    ~Application();
    
    int run(int argc, char** argv);
    virtual void CreateScene();  //Must be overriden to get the desired results

    //Toolbars, buttons, other widgets
    Fl_Button* btnPoint;
    Fl_Button* btnLine;
    Fl_Button* btnTriangle;
    Fl_Button* btnSquare;
    Fl_Button* btnPolygon;
    Fl_Button* btnBox;
    Fl_Button* btnCylinder;
    Fl_Button* btnSphere;
    Fl_Button* btnCone;
    Fl_Button* btnTours;
    Fl_Button* btnParaboloid;
    Fl_Button* btnAlignToPlane;
    Fl_Button* btnExtract;

    Fl_Group* grpFLGW;
    Fl_Group* grp2DPrimatives;
    Fl_Group* grpBasic;
    Fl_Group* grpAdvanced;
    Fl_Group* grpAlignment;
    Fl_Group* grpOperations;

    Fl_Tile* tilMainWindow;
    Fl_Group* tilGToolBars; //Widget toolbars left side of glfw window
    Fl_Group* tilGglfw; //Widget toolbars left side of glfw window

    GLFWwindow* pWindow;
    Fl_Tabs* tabToolbars;
    Fl_Window* pfltkWindow;
    Fl_Menu_Bar* barStatus;
    Fl_Menu_Bar* barMenu;
    Fl_Menu_Item menu_[];

    static void createBox_cb(Fl_Button*, void*);
    static void createCylinder_cb(Fl_Button*, void*);
    static void createSphere_cb(Fl_Button*, void*);
    static void createCone_cb(Fl_Button*, void*);
    static void createTours_cb(Fl_Button*, void*);
    static void createPoint_cb(Fl_Button*, void*);
    static void createLine_cb(Fl_Button*, void*);
    static void createTriangle_cb(Fl_Button*, void*);
    static void createSquare_cb(Fl_Button*, void*);
    static void createPolygon_cb(Fl_Button*, void*);
    static void createParaboloid_cb(Fl_Button*, void*);
    static void AlignToPlane_cb(Fl_Button*, void*);
    static void Extract_cb(Fl_Button*, void*);

};



#endif

