// generated by Fast Light User Interface Designer (fluid) version 1,0400

#ifndef Fr_GL4Window_h
#define Fr_GL4Window_h
#include <FL/Fl.H>
#include<Fr_Core.h>
#include<Fr_GL3Window.h>
#include <FL/Fl_Window.H>
extern Fl_Window *pfltkWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *barStatus;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabToolbars;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btnPoint;
extern Fl_Button *btnLine;
extern Fl_Button *btnTriangle;
extern Fl_Button *btnSquare;
extern Fl_Button *btnPolygon;
extern Fl_Button *btnBox;
extern Fl_Button *btnCylinder;
extern Fl_Button *btnSphere;
extern Fl_Button *btnCone;
extern Fl_Button *btnTours;
extern Fl_Button *btnTours;
#include <FL/Fl_Tile.H>
extern Fl_Group *grpFLGW;
extern GLFWwindow *pWindow;
Fr_GL3Window* Create_App();
extern Fl_Menu_Item menu_[];
void createBox_cb();
void createCylinder_cb();
void createSphere_cb();
void createCone_cb();
void createTours_cb();
void createPoint_cb();
void createLine_cb();
void createTriangle_cb();
void createSquare_cb();
void createPolygon_cb();
#endif
